# Generated by Django 6.0.7 on 2026-07-15 17:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('payments', '0001_initial'),
        ('subscriptions', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='subscription',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='subscriptions.subscription'),
        ),
        migrations.AddIndex(
            model_name='payment',
            index=models.Index(fields=['status', '-paid_at'], name='payments_pa_status_d5e903_idx'),
        ),
    ]
