# Generated by Django 6.0.7 on 2026-07-15 17:25

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PlatformSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('site_name', models.CharField(default='QueueLess Nepal', max_length=100)),
                ('support_email', models.EmailField(default='support@queueless.np', max_length=254)),
                ('maintenance_mode', models.BooleanField(default=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name_plural': 'Platform settings',
            },
        ),
        migrations.CreateModel(
            name='ActivityLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('action', models.CharField(choices=[('login', 'Login'), ('org_approved', 'Organization Approved'), ('org_suspended', 'Organization Suspended'), ('org_reactivated', 'Organization Reactivated'), ('org_created', 'Organization Created'), ('org_deleted', 'Organization Deleted'), ('user_blocked', 'User Blocked'), ('user_unblocked', 'User Unblocked'), ('password_reset', 'Password Reset'), ('subscription_renewed', 'Subscription Renewed'), ('subscription_assigned', 'Subscription Assigned'), ('payment_recorded', 'Payment Recorded'), ('announcement_sent', 'Announcement Sent')], max_length=30)),
                ('description', models.CharField(max_length=255)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('actor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='activity_logs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['action', '-created_at'], name='core_activi_action_a01617_idx')],
            },
        ),
    ]
