# Generated by Django 6.0.7 on 2026-07-18 02:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0001_initial'),
        ('staff', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='staffprofile',
            name='service',
            field=models.ForeignKey(blank=True, help_text='If set, this staff member works one dedicated counter and can only book walk-in tokens for this service.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_staff', to='services.service'),
        ),
    ]
