# Generated by Django 6.0.7 on 2026-07-15 16:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='organization',
            name='allow_customer_rebooking',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='organization',
            name='max_active_tokens_per_customer',
            field=models.PositiveSmallIntegerField(default=1),
        ),
        migrations.AddField(
            model_name='organization',
            name='notify_daily_summary',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='organization',
            name='notify_on_new_booking',
            field=models.BooleanField(default=True),
        ),
    ]
