# Generated by Django 6.0.7 on 2026-07-15 16:00

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('organizations', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=150)),
                ('description', models.TextField(blank=True)),
                ('average_service_minutes', models.PositiveIntegerField(default=10, help_text='Average time to serve one customer, used to estimate wait time.')),
                ('daily_token_limit', models.PositiveIntegerField(default=100, help_text='Maximum tokens accepted per day for this service.')),
                ('is_active', models.BooleanField(default=True)),
                ('department', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='services', to='organizations.department')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='services', to='organizations.organization')),
            ],
            options={
                'ordering': ['name'],
                'indexes': [models.Index(fields=['organization', 'is_active'], name='services_se_organiz_6efc8e_idx')],
                'constraints': [models.UniqueConstraint(fields=('organization', 'name'), name='unique_service_per_org')],
            },
        ),
    ]
