# Generated by Django 6.0.7 on 2026-07-15 17:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('queue_management', '0002_queue_priority_token_served_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='token',
            name='transferred_from',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transferred_to_tokens', to='queue_management.token'),
        ),
    ]
