# Generated by Django 6.0.7 on 2026-07-18 04:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('queue_management', '0003_token_transferred_from'),
    ]

    operations = [
        migrations.AddField(
            model_name='token',
            name='priority',
            field=models.CharField(choices=[('normal', 'Normal'), ('high', 'High'), ('urgent', 'Urgent')], default='normal', max_length=10),
        ),
    ]
